# Generated by Django 4.2.1 on 2023-08-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'destinos',
                'ordering': ('identificador',),
            },
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ('marca',),
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'ordering': ('modelo',),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('destino_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinos.destino')),
                ('ci', models.CharField(max_length=8, unique=True, verbose_name='Cédula')),
                ('nombre1', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre')),
                ('apellido1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
            bases=('destinos.destino',),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('destino_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinos.destino')),
                ('nombre_unidad', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('telefonos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfonos')),
            ],
            options={
                'verbose_name': 'unidad',
                'verbose_name_plural': 'unidades',
            },
            bases=('destinos.destino',),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('destino_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinos.destino')),
                ('matricula', models.CharField(max_length=7, unique=True, verbose_name='Matrícula')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.marcavehiculo', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.modelovehiculo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
            },
            bases=('destinos.destino',),
        ),
    ]
