# Generated by Django 4.2.1 on 2023-08-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTetra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'marca tetra',
                'verbose_name_plural': 'marcas tetra',
                'ordering': ('marca',),
            },
        ),
        migrations.CreateModel(
            name='ModeloTetra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60, unique=True, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'modelo tetra',
                'verbose_name_plural': 'modelos tetra',
                'ordering': ('modelo',),
            },
        ),
        migrations.CreateModel(
            name='TipoTetra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'tipo tetra',
                'verbose_name_plural': 'tipos tetra',
                'ordering': ('tipo',),
            },
        ),
        migrations.CreateModel(
            name='Tetra',
            fields=[
                ('equipo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipos.equipo')),
                ('nombre', models.CharField(max_length=15, unique=True, verbose_name='Nombre')),
                ('issi', models.CharField(max_length=5, unique=True, verbose_name='ISSI')),
                ('tei', models.CharField(max_length=15, unique=True, verbose_name='TEI')),
                ('serie', models.CharField(max_length=15, unique=True, verbose_name='Nro. Serie')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tetras', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edidión')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tetras.marcatetra', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tetras.modelotetra', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'equipo tetra',
                'verbose_name_plural': 'equipos tetra',
                'ordering': ('issi', 'tei'),
            },
            bases=('equipos.equipo',),
        ),
    ]
